title: devlopr starter
email: johndoe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# theme: devlopr
# Build settings
theme: devlopr

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# pagination of posts
paginate: 10
per_page: 6
paginate_path: "/blog/page/:num/"

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact

author_logo: profile.png
author:  John Doe
author_bio: Web Developer, Designer
author_email: johndoe@gmail.com
author_location: India
author_website_url: "https://sujaykundu.com"

# social links
twitter_username: johndoe
github_username:  johndoe
facebook_username: johndoe
linkedin_username: johndoe
behance_username: johndoe
instagram_username: johndoe
medium_username: johndoe
telegram_username: johndoe
dribbble_username: johndoe
flickr_username: johndoe

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Web Developer
              description: I build and design google's websites
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Web Developer
              description: I build and design microsoft's websites
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: false

author_project_details:
              - project_thumbnail: projects/devlopr.png
                project_title: Devlopr Jekyll
                project_description: A Jekyll Theme built for Developers
                project_url: https://devlopr.netlify.com
                project_repo_url: https://github.com/sujaykundu777/devlopr-jekyll
                project_tags: Theme, SSG, Web App, Ruby
                visibility: true
              - project_thumbnail: projects/hackify.png
                project_title: Hackify Atom Theme
                project_description: A Dark Hacker Theme for Atom Editor
                project_url: https://atom.io/themes/hackify-ui
                project_repo_url: https://github.com/sujaykundu777/hackify-ui
                project_tags: Theme, Atom Editor Plugin
                visibility: false
              - project_thumbnail: projects/gamershub.png
                project_title: Gamers Hub
                project_description: A Platform for Gamers and Game Devs to share Gaming Related links
                project_url: https://gamershub.in
                project_repo_url: https://github.com/Gamers-Hub/gamers-hub
                project_tags: Web App, React, Meteor, Javascript
                visibility: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

destination: ./build
